<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DummyUserSeeder extends Seeder
{
    public function run(): void
    {
        // ==========================================
        // 1. BERSIHKAN DATA LAMA
        // ==========================================
        DB::statement('SET FOREIGN_KEY_CHECKS = 0;');
        DB::table('setorans')->truncate();
        DB::table('users')->whereIn('role', ['stakeholder', 'pengepul', 'masyarakat'])->delete();
        DB::statement('SET FOREIGN_KEY_CHECKS = 1;');

        // ==========================================
        // 2. SUNTIK DATA AKTOR (USERS)
        // ==========================================
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'PT Hijau Energi Nusantara (Pusat)',
                'email' => 'stakeholder@hen.com',
                'role' => 'stakeholder',
                'kategori' => 'Korporasi',
                'latitude' => -7.55000000,
                'longitude' => 110.82000000,
                'harga_per_liter' => null,
                'kapasitas' => null,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'name' => 'Hub Solo Utara (Budi)',
                'email' => 'pengepul1@hen.com',
                'role' => 'pengepul',
                'kategori' => 'Pengepul Utama',
                'latitude' => -7.54200000,
                'longitude' => 110.81500000,
                'harga_per_liter' => 12000,
                'kapasitas' => 1000.00,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'name' => 'Hub Solo Selatan (Siti)',
                'email' => 'pengepul2@hen.com',
                'role' => 'pengepul',
                'kategori' => 'Pengepul Utama',
                'latitude' => -7.58000000,
                'longitude' => 110.83000000,
                'harga_per_liter' => 12000,
                'kapasitas' => 1500.00,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'name' => 'Resto Ayam Goreng Kampung',
                'email' => 'warga1@gmail.com',
                'role' => 'masyarakat',
                'kategori' => 'Restoran',
                'latitude' => -7.53800000,
                'longitude' => 110.80000000,
                'harga_per_liter' => null,
                'kapasitas' => null,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'name' => 'UMKM Gorengan Berkah',
                'email' => 'warga2@gmail.com',
                'role' => 'masyarakat',
                'kategori' => 'Rumah Tangga',
                'latitude' => -7.55500000,
                'longitude' => 110.84000000,
                'harga_per_liter' => null,
                'kapasitas' => null,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'name' => 'Hotel Grand Solo',
                'email' => 'warga3@gmail.com',
                'role' => 'masyarakat',
                'kategori' => 'Hotel',
                'latitude' => -7.56700000,
                'longitude' => 110.81200000,
                'harga_per_liter' => null,
                'kapasitas' => null,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);

        // ==========================================
        // 3. SUNTIK DATA TRANSAKSI (SETORAN)
        // ==========================================
        DB::table('setorans')->insert([
            // BULAN MARET 2026
            [
                'id' => 1,
                'masyarakat_id' => 4,
                'pengepul_id' => 2,
                'liter_estimasi' => 50.00,
                'tanggal_penjemputan' => '2026-03-10',
                'jam_penjemputan' => '10:00:00',
                'status' => 'selesai',
                'liter_bersih' => 48.00,
                'endapan' => 2.00,
                'harga_dibayar' => 240000,
                'kadar_air' => 0.20,
                'ffa' => 1.50,
                'kotoran' => 0.10,
                'grade' => 'Grade A',
                'liter_final' => 48.00,
                'created_at' => '2026-03-10 10:00:00',
                'updated_at' => '2026-03-10 14:00:00',
            ],
            [
                'id' => 2,
                'masyarakat_id' => 5,
                'pengepul_id' => 3,
                'liter_estimasi' => 100.00,
                'tanggal_penjemputan' => '2026-03-25',
                'jam_penjemputan' => '11:00:00',
                'status' => 'selesai',
                'liter_bersih' => 96.00,
                'endapan' => 4.00,
                'harga_dibayar' => 480000,
                'kadar_air' => 0.50,
                'ffa' => 2.10,
                'kotoran' => 0.30,
                'grade' => 'Grade B',
                'liter_final' => 96.00,
                'created_at' => '2026-03-25 11:00:00',
                'updated_at' => '2026-03-25 15:00:00',
            ],
            // BULAN APRIL 2026
            [
                'id' => 3,
                'masyarakat_id' => 6,
                'pengepul_id' => 2,
                'liter_estimasi' => 150.00,
                'tanggal_penjemputan' => '2026-04-05',
                'jam_penjemputan' => '09:30:00',
                'status' => 'selesai',
                'liter_bersih' => 145.00,
                'endapan' => 5.00,
                'harga_dibayar' => 725000,
                'kadar_air' => 0.10,
                'ffa' => 1.20,
                'kotoran' => 0.10,
                'grade' => 'Grade A',
                'liter_final' => 145.00,
                'created_at' => '2026-04-05 09:30:00',
                'updated_at' => '2026-04-05 13:00:00',
            ],
            [
                'id' => 4,
                'masyarakat_id' => 4,
                'pengepul_id' => 2,
                'liter_estimasi' => 90.00,
                'tanggal_penjemputan' => '2026-04-18',
                'jam_penjemputan' => '14:00:00',
                'status' => 'selesai',
                'liter_bersih' => 85.00,
                'endapan' => 5.00,
                'harga_dibayar' => 425000,
                'kadar_air' => 0.40,
                'ffa' => 1.90,
                'kotoran' => 0.20,
                'grade' => 'Grade B',
                'liter_final' => 85.00,
                'created_at' => '2026-04-18 14:00:00',
                'updated_at' => '2026-04-18 16:30:00',
            ],
            // BULAN MEI 2026
            [
                'id' => 5,
                'masyarakat_id' => 5,
                'pengepul_id' => 3,
                'liter_estimasi' => 200.00,
                'tanggal_penjemputan' => '2026-05-12',
                'jam_penjemputan' => '08:00:00',
                'status' => 'selesai',
                'liter_bersih' => 190.00,
                'endapan' => 10.00,
                'harga_dibayar' => 950000,
                'kadar_air' => 0.30,
                'ffa' => 1.40,
                'kotoran' => 0.20,
                'grade' => 'Grade A',
                'liter_final' => 190.00,
                'created_at' => '2026-05-12 08:00:00',
                'updated_at' => '2026-05-12 11:00:00',
            ],
            [
                'id' => 6,
                'masyarakat_id' => 6,
                'pengepul_id' => 3,
                'liter_estimasi' => 180.00,
                'tanggal_penjemputan' => '2026-05-28',
                'jam_penjemputan' => '15:00:00',
                'status' => 'selesai',
                'liter_bersih' => 180.00,
                'endapan' => 0.00,
                'harga_dibayar' => 900000,
                'kadar_air' => 0.20,
                'ffa' => 1.10,
                'kotoran' => 0.10,
                'grade' => 'Grade A',
                'liter_final' => 180.00,
                'created_at' => '2026-05-28 15:00:00',
                'updated_at' => '2026-05-28 17:00:00',
            ],
            // BULAN JUNI 2026
            [
                'id' => 7,
                'masyarakat_id' => 4,
                'pengepul_id' => 2,
                'liter_estimasi' => 250.00,
                'tanggal_penjemputan' => '2026-06-05',
                'jam_penjemputan' => '10:00:00',
                'status' => 'selesai',
                'liter_bersih' => 242.00,
                'endapan' => 8.00,
                'harga_dibayar' => 1210000,
                'kadar_air' => 0.20,
                'ffa' => 1.30,
                'kotoran' => 0.10,
                'grade' => 'Grade A',
                'liter_final' => 242.00,
                'created_at' => '2026-06-05 10:00:00',
                'updated_at' => '2026-06-05 12:00:00',
            ],
            [
                'id' => 8,
                'masyarakat_id' => 5,
                'pengepul_id' => 3,
                'liter_estimasi' => 300.00,
                'tanggal_penjemputan' => '2026-06-12',
                'jam_penjemputan' => '11:15:00',
                'status' => 'selesai',
                'liter_bersih' => 290.00,
                'endapan' => 10.00,
                'harga_dibayar' => 1450000,
                'kadar_air' => 0.60,
                'ffa' => 2.50,
                'kotoran' => 0.40,
                'grade' => 'Grade C',
                'liter_final' => 290.00,
                'created_at' => '2026-06-12 11:15:00',
                'updated_at' => '2026-06-12 14:00:00',
            ],
            // DATA ANTRIAN PROSES (Pending)
            [
                'id' => 9,
                'masyarakat_id' => 6,
                'pengepul_id' => 2,
                'liter_estimasi' => 120.00,
                'tanggal_penjemputan' => '2026-06-22',
                'jam_penjemputan' => '09:00:00',
                'status' => 'pending',
                'liter_bersih' => null,
                'endapan' => null,
                'harga_dibayar' => null,
                'kadar_air' => null,
                'ffa' => null,
                'kotoran' => null,
                'grade' => null,
                'liter_final' => null,
                'created_at' => '2026-06-22 09:00:00',
                'updated_at' => '2026-06-22 09:00:00',
            ],
            [
                'id' => 10,
                'masyarakat_id' => 4,
                'pengepul_id' => 3,
                'liter_estimasi' => 85.00,
                'tanggal_penjemputan' => '2026-06-22',
                'jam_penjemputan' => '14:20:00',
                'status' => 'pending',
                'liter_bersih' => null,
                'endapan' => null,
                'harga_dibayar' => null,
                'kadar_air' => null,
                'ffa' => null,
                'kotoran' => null,
                'grade' => null,
                'liter_final' => null,
                'created_at' => '2026-06-22 14:20:00',
                'updated_at' => '2026-06-22 14:20:00',
            ]
        ]);
    }
}